/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// User with all belonging objects
type UserDetailsDto struct {
	Id          string         `json:"id,omitempty"`
	UserName    string         `json:"userName,omitempty"`
	FirstName   string         `json:"firstName,omitempty"`
	LastName    string         `json:"lastName,omitempty"`
	Email       string         `json:"email,omitempty"`
	DateCreated time.Time      `json:"dateCreated,omitempty"`
	DateDeleted time.Time      `json:"dateDeleted,omitempty"`
	CreatedBy   *UserReference `json:"createdBy,omitempty"`
	Role        string         `json:"role,omitempty"`
	Timezone    string         `json:"timezone,omitempty"`
	Note        string         `json:"note,omitempty"`
	// Default: false
	Terminologist        bool                     `json:"terminologist,omitempty"`
	SourceLangs          []string                 `json:"sourceLangs,omitempty"`
	TargetLangs          []string                 `json:"targetLangs,omitempty"`
	WorkflowSteps        []WorkflowStepReference  `json:"workflowSteps,omitempty"`
	Clients              []ClientReference        `json:"clients,omitempty"`
	Domains              []DomainReference        `json:"domains,omitempty"`
	SubDomains           []SubDomainReference     `json:"subDomains,omitempty"`
	ProjectBusinessUnits []BusinessUnitReference  `json:"projectBusinessUnits,omitempty"`
	Organization         *IdReference             `json:"organization,omitempty"`
	PriceList            *PriceListReference      `json:"priceList,omitempty"`
	NetRateScheme        *DiscountSchemeReference `json:"netRateScheme,omitempty"`
	Active               bool                     `json:"active,omitempty"`
}
