/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EditQaSettingsDto struct {
	// Default: false
	EmptyTranslation bool `json:"emptyTranslation,omitempty"`
	// Default: false
	InconsistentTranslation bool `json:"inconsistentTranslation,omitempty"`
	// Default: false
	JoinTags bool `json:"joinTags,omitempty"`
	// Default: false
	MissingNumbers bool `json:"missingNumbers,omitempty"`
	// Default: false
	SegmentNotConfirmed bool `json:"segmentNotConfirmed,omitempty"`
	// Default: false
	Terminology bool `json:"terminology,omitempty"`
	// Default: false
	MultipleSpaces bool `json:"multipleSpaces,omitempty"`
	// Default: false
	TrailingSpace bool `json:"trailingSpace,omitempty"`
	// Default: false
	TrailingPunctuation bool  `json:"trailingPunctuation,omitempty"`
	TargetLengthMax     int32 `json:"targetLengthMax,omitempty"`
	// Default: false
	Formatting bool `json:"formatting,omitempty"`
	// Default: false
	UnresolvedComment bool `json:"unresolvedComment,omitempty"`
	// Default: false
	EmptyPairTags bool `json:"emptyPairTags,omitempty"`
	// Linguists may not set jobs with unresolved QA warnings to Completed. default value: false
	StrictJobStatus  bool     `json:"strictJobStatus,omitempty"`
	ForbiddenStrings []string `json:"forbiddenStrings,omitempty"`
	// Default: false
	ExcludeLockedSegments bool `json:"excludeLockedSegments,omitempty"`
	// Default: false
	IgnoreNotApprovedTerms bool `json:"ignoreNotApprovedTerms,omitempty"`
	// Default: false
	SpellCheck bool `json:"spellCheck,omitempty"`
	// Default: false
	RepeatedWords bool `json:"repeatedWords,omitempty"`
	// Default: false
	InconsistentTagContent bool `json:"inconsistentTagContent,omitempty"`
	// Default: false
	EmptyTagContent bool `json:"emptyTagContent,omitempty"`
	// Default: false
	XliffTags bool `json:"xliffTags,omitempty"`
	// Default: false
	ForbiddenTerms      bool    `json:"forbiddenTerms,omitempty"`
	TargetLengthPercent float64 `json:"targetLengthPercent,omitempty"`
	// Default: false
	TargetLengthPerSegment bool `json:"targetLengthPerSegment,omitempty"`
	// Default: false
	NewerAtPrecedingWorkflowStep bool `json:"newerAtPrecedingWorkflowStep,omitempty"`
	// Default: false
	LeadingAndTrailingSpaces bool            `json:"leadingAndTrailingSpaces,omitempty"`
	MoraviaQA                *MoraviaQaDto   `json:"moraviaQA,omitempty"`
	Regexp                   *RegexpCheckDto `json:"regexp,omitempty"`
}
