/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ExportByQueryDto struct {
	ExportTargetLangs []string      `json:"exportTargetLangs"`
	Queries           []string      `json:"queries"`
	QueryLangs        []string      `json:"queryLangs"`
	CreatedAtMin      time.Time     `json:"createdAtMin,omitempty"`
	CreatedAtMax      time.Time     `json:"createdAtMax,omitempty"`
	ModifiedAtMin     time.Time     `json:"modifiedAtMin,omitempty"`
	ModifiedAtMax     time.Time     `json:"modifiedAtMax,omitempty"`
	CreatedBy         *IdReference  `json:"createdBy,omitempty"`
	ModifiedBy        *IdReference  `json:"modifiedBy,omitempty"`
	Filename          string        `json:"filename,omitempty"`
	Project           *UidReference `json:"project,omitempty"`
	CallbackUrl       string        `json:"callbackUrl,omitempty"`
}
