/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectTemplateEditDto struct {
	Name         string   `json:"name,omitempty"`
	TemplateName string   `json:"templateName"`
	SourceLang   string   `json:"sourceLang,omitempty"`
	TargetLangs  []string `json:"targetLangs,omitempty"`
	// use to notify assigned providers,         notificationIntervalInMinutes 0 or empty value means immediate notification to all providers
	NotifyProvider   *ProjectTemplateNotifyProviderDto `json:"notifyProvider,omitempty"`
	WorkFlowSettings []WorkflowStepSettingsEditDto     `json:"workFlowSettings,omitempty"`
	Client           *IdReference                      `json:"client,omitempty"`
	CostCenter       *IdReference                      `json:"costCenter,omitempty"`
	BusinessUnit     *IdReference                      `json:"businessUnit,omitempty"`
	Domain           *IdReference                      `json:"domain,omitempty"`
	SubDomain        *IdReference                      `json:"subDomain,omitempty"`
	Note             string                            `json:"note,omitempty"`
	// only use for projects without workflows; otherwise specify in the workflowSettings object
	AssignedTo []ProjectTemplateWorkflowSettingsAssignedToDto `json:"assignedTo,omitempty"`
}
