/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SearchTmResponseDto struct {
	SegmentId    string                  `json:"segmentId,omitempty"`
	Source       *SearchTmSegmentDto     `json:"source,omitempty"`
	Translations []SearchTmSegmentDto    `json:"translations,omitempty"`
	TransMemory  *SearchTmTransMemoryDto `json:"transMemory,omitempty"`
	GrossScore   float64                 `json:"grossScore,omitempty"`
	Score        float64                 `json:"score,omitempty"`
	SubSegment   bool                    `json:"subSegment,omitempty"`
}
