/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EditProjectSecuritySettingsDto struct {
	// Default: false
	TranslationMemoryDownloadEnabled bool `json:"translationMemoryDownloadEnabled,omitempty"`
	// Default: false
	WebEditorEnabledForLinguists bool `json:"webEditorEnabledForLinguists,omitempty"`
	// Default: false
	ShowUserDataToLinguists bool `json:"showUserDataToLinguists,omitempty"`
	// Default: false
	EmailNotifications bool `json:"emailNotifications,omitempty"`
	// Default: false
	StrictWorkflowFinish bool `json:"strictWorkflowFinish,omitempty"`
	// Default: false
	UseVendors bool `json:"useVendors,omitempty"`
	// Default: false
	LinguistsMayEditLockedSegments bool `json:"linguistsMayEditLockedSegments,omitempty"`
	// Default: true
	LinguistsMaySetAutoPropagation bool `json:"linguistsMaySetAutoPropagation,omitempty"`
	// Default: true
	UsersMaySetAutoPropagation bool `json:"usersMaySetAutoPropagation,omitempty"`
}
