/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Xlf2SettingsDto struct {
	// Default: true
	ImportNotes bool `json:"importNotes,omitempty"`
	// Default: true
	SaveConfirmedSegments bool `json:"saveConfirmedSegments,omitempty"`
	// Default: true
	Segmentation bool `json:"segmentation,omitempty"`
	// Default: false
	LineBreakTags bool `json:"lineBreakTags,omitempty"`
	// Default: true
	PreserveWhitespace bool `json:"preserveWhitespace,omitempty"`
	// Default: true
	CopySourceToTargetIfNotImported bool `json:"copySourceToTargetIfNotImported,omitempty"`
	// Default: true
	RespectTranslateAttr bool   `json:"respectTranslateAttr,omitempty"`
	SkipImportRules      string `json:"skipImportRules,omitempty"`
	// Default: state=final
	ImportAsConfirmedRules string `json:"importAsConfirmedRules,omitempty"`
	ImportAsLockedRules    string `json:"importAsLockedRules,omitempty"`
	// Default: state=final
	ExportAttrsWhenConfirmedAndLocked string `json:"exportAttrsWhenConfirmedAndLocked,omitempty"`
	// Default: state=final
	ExportAttrsWhenConfirmedAndNotLocked    string `json:"exportAttrsWhenConfirmedAndNotLocked,omitempty"`
	ExportAttrsWhenNotConfirmedAndLocked    string `json:"exportAttrsWhenNotConfirmedAndLocked,omitempty"`
	ExportAttrsWhenNotConfirmedAndNotLocked string `json:"exportAttrsWhenNotConfirmedAndNotLocked,omitempty"`
	ContextKeyXPath                         string `json:"contextKeyXPath,omitempty"`
}
