/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JobSegmentDto struct {
	Id            string           `json:"id,omitempty"`
	Source        string           `json:"source,omitempty"`
	Translation   string           `json:"translation,omitempty"`
	CreatedAt     int64            `json:"createdAt,omitempty"`
	ModifiedAt    int64            `json:"modifiedAt,omitempty"`
	CreatedBy     *UserReference   `json:"createdBy,omitempty"`
	ModifiedBy    *UserReference   `json:"modifiedBy,omitempty"`
	WorkflowLevel int32            `json:"workflowLevel,omitempty"`
	WorkflowStep  *WorkflowStepDto `json:"workflowStep,omitempty"`
}
