/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type XmlSettingsDto struct {
	// Default: PLAIN
	RulesFormat string `json:"rulesFormat,omitempty"`
	// Default: *, example: \"para,heading\"
	IncludeElementsPlain string `json:"includeElementsPlain,omitempty"`
	// Example: \"script,par\"
	ExcludeElementsPlain string `json:"excludeElementsPlain,omitempty"`
	// Example: \"title\"
	IncludeAttributesPlain string `json:"includeAttributesPlain,omitempty"`
	// Example: \"lang,href\"
	ExcludeAttributesPlain string `json:"excludeAttributesPlain,omitempty"`
	// Example: \"tt,b\"
	InlineElementsNonTranslatablePlain string `json:"inlineElementsNonTranslatablePlain,omitempty"`
	InlineElementsPlain                string `json:"inlineElementsPlain,omitempty"`
	// Default: false
	InlineElementsAutoPlain bool `json:"inlineElementsAutoPlain,omitempty"`
	// Example: \"tt,b\"
	HtmlSubfilterElementsPlain         string `json:"htmlSubfilterElementsPlain,omitempty"`
	Entities                           bool   `json:"entities,omitempty"`
	LockElementsPlain                  string `json:"lockElementsPlain,omitempty"`
	LockAttributesPlain                string `json:"lockAttributesPlain,omitempty"`
	IncludeXPath                       string `json:"includeXPath,omitempty"`
	InlineElementsXpath                string `json:"inlineElementsXpath,omitempty"`
	InlineElementsNonTranslatableXPath string `json:"inlineElementsNonTranslatableXPath,omitempty"`
	InlineElementsAutoXPath            bool   `json:"inlineElementsAutoXPath,omitempty"`
	HtmlSubfilterElementsXpath         string `json:"htmlSubfilterElementsXpath,omitempty"`
	LockXPath                          string `json:"lockXPath,omitempty"`
	// Default: true
	Segmentation            bool   `json:"segmentation,omitempty"`
	TagRegexp               string `json:"tagRegexp,omitempty"`
	ContextNoteXpath        string `json:"contextNoteXpath,omitempty"`
	MaxLenXPath             string `json:"maxLenXPath,omitempty"`
	PreserveWhitespaceXPath string `json:"preserveWhitespaceXPath,omitempty"`
	PreserveCharEntities    string `json:"preserveCharEntities,omitempty"`
	ContextKeyXPath         string `json:"contextKeyXPath,omitempty"`
	XslUrl                  string `json:"xslUrl,omitempty"`
	// Default: true
	ImportComments bool `json:"importComments,omitempty"`
}
