/*
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](https://get-help.memsource.com).
 *
 * API version: All
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Vendor struct {
	Uid         string                   `json:"uid,omitempty"`
	InternalId  int32                    `json:"internalId,omitempty"`
	Id          string                   `json:"id,omitempty"`
	Name        string                   `json:"name,omitempty"`
	DateCreated time.Time                `json:"dateCreated,omitempty"`
	Domain      *DomainReference         `json:"domain,omitempty"`
	SubDomain   *SubDomainReference      `json:"subDomain,omitempty"`
	Owner       *UserReference           `json:"owner,omitempty"`
	SourceLang  string                   `json:"sourceLang,omitempty"`
	TargetLangs []string                 `json:"targetLangs,omitempty"`
	References  []ReferenceFileReference `json:"references,omitempty"`
	// Response differs based on user's role
	UserRole string `json:"userRole,omitempty"`
	// Default: false
	Shared        bool                   `json:"shared,omitempty"`
	Progress      *ProgressDto           `json:"progress,omitempty"`
	Client        *ClientReference       `json:"client,omitempty"`
	CostCenter    *CostCenterReference   `json:"costCenter,omitempty"`
	BusinessUnit  *BusinessUnitReference `json:"businessUnit,omitempty"`
	DateDue       time.Time              `json:"dateDue,omitempty"`
	Status        string                 `json:"status,omitempty"`
	PurchaseOrder string                 `json:"purchaseOrder,omitempty"`
	// Default: false
	IsPublishedOnJobBoard     bool                             `json:"isPublishedOnJobBoard,omitempty"`
	Note                      string                           `json:"note,omitempty"`
	CreatedBy                 *UserReference                   `json:"createdBy,omitempty"`
	QualityAssuranceSettings  *IdReference                     `json:"qualityAssuranceSettings,omitempty"`
	WorkflowSteps             []ProjectWorkflowStepDto         `json:"workflowSteps,omitempty"`
	AnalyseSettings           *IdReference                     `json:"analyseSettings,omitempty"`
	AccessSettings            *IdReference                     `json:"accessSettings,omitempty"`
	FinancialSettings         *IdReference                     `json:"financialSettings,omitempty"`
	MtSettingsPerLanguageList []MtSettingsPerLanguageReference `json:"mtSettingsPerLanguageList,omitempty"`
	BuyerOwner                *User                            `json:"buyerOwner,omitempty"`
	Buyer                     *BuyerReference                  `json:"buyer,omitempty"`
}
